baseURL = 'https://ppepin.github.io/portfolio/'
locale = 'en-us'
title = 'Patrick Pepin | Portfolio'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "Amusements"
    url = "/amusements/"
    weight = 4
